server:
  port: 8888

spring:
  application:
    name: WordKeeper

  profiles:
    active: dev

mybatis:
  #domain对象的包
  type-aliases-package: com.xmu.wordkeeper.domain
  #mapper。xml所在的位置
  mapper-locations: classpath:com.xmu.wordkeeper.mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true